/**
 * Data types for rendered proposals (generated by Claude).
 * Maps to the HTML proposal template structure: cover, 12 numbered sections, contact footer.
 */

export interface ProposalTableData {
  headersKa: string[];
  headersEn: string[];
  rowsKa: string[][];
  rowsEn: string[][];
}

export interface KeyStats {
  [label: string]: string;
}

export interface ProposalSection {
  number: string; // "01" to "12"
  titleKa: string;
  titleEn: string;
  headlineKa: string;
  headlineEn: string;
  keyStatsKa: KeyStats;
  keyStatsEn: KeyStats;
  contentKa: string;
  contentEn: string;
  type: "text" | "table" | "cards" | "metrics";
  // Present only when type === "table"
  tableData?: ProposalTableData;
}

export interface ProposalCover {
  taglineKa: string;
  taglineEn: string;
  summaryKa: string;
  summaryEn: string;
  year: number;
}

export interface ProposalContact {
  name: string;
  title: string;
  email: string;
  location: string;
}

export interface ProposalData {
  cover: ProposalCover;
  sections: ProposalSection[];
  contact: ProposalContact;
}
